version: "3.1"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
